### ISSUE TITLE
Configuration Not Persisting After Initial Setup

### ISSUE THREAD

**Issue by nicmela** [nliaudat/aioted_manager#1]
After the initial configuration of the integration, any subsequent updates to the configuration are not saved. Additionally, the default values for scan_interval, log_on_csv, and save_images are reset to their defaults. This behavior persists even after restarting Home Assistant.

Steps to Reproduce:

1. Install and configure the integration via HACS.

2. Modify configuration options such as scan_interval, log_on_csv, or save_images.

3. Save the changes.

4. Observe that the changes are not retained, and the default values are restored.

Expected Behavior:

Configuration changes should persist across restarts and not revert to default values.

Additional Information:

Home Assistant version: 2025.1.4

Integration version: 1.5

Installation method: docker

**Comment by nliaudat** [comment]
Can you send logs ? 
It's working great on my lab and prod environnement

**Comment by nicmela** [comment]
Sure.. 😊 I activated debug and tried to edit again. I even added a new configuration from scratch... Same problem. 
Here's the logs:
```
Registratore: homeassistant.helpers.entity
Fonte: helpers/entity.py:960
Prima occorrenza: 08:38:04 (4 occorrenze)
Ultimo accesso: 20:37:54

Update for sensor.meter_collector_consumo_h2o fails
Traceback (most recent call last):
  File "/config/custom_components/aioted_manager/sensor.py", line 146, in _async_update
    self.available = False
    ^^^^^^^^^^^^^^
AttributeError: property 'available' of 'MeterCollectorSensor' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/aioted_manager/sensor.py", line 171, in _async_update
    self.available = False
    ^^^^^^^^^^^^^^
AttributeError: property 'available' of 'MeterCollectorSensor' object has no setter
``` 
```
Questo errore ha avuto origine da un'integrazione personalizzata.

Registratore: custom_components.aioted_manager.sensor
Fonte: custom_components/aioted_manager/sensor.py:168
Integrazione: AIOTED Manager (documentazione, problemi)
Prima occorrenza: 08:38:04 (4 occorrenze)
Ultimo accesso: 20:37:54

Unexpected error during update: property 'available' of 'MeterCollectorSensor' object has no setter
```

**Comment by nliaudat** [comment]
I corrected the https://github.com/nliaudat/aioted_manager/blob/main/custom_components/aioted_manager/sensor.py

But the error is more that the raw value retrieved is not readable. 
The sensor set it to disable in that case. The error was it was setting "available" property instead of enabled

**Comment by nicmela** [comment]
I just redownload from hacs. But as you can see I still get the anomaly while trying to update values.

[error_log.txt](https://github.com/user-attachments/files/19811493/error_log.txt)

https://github.com/user-attachments/assets/523bdcda-b51f-428b-8223-a4f5b4049753

Is there something I can do to help finding the issue?

**Comment by nliaudat** [comment]
Ok, 
I found the error. 

Some setup configuration like IP, name and device class should be only done in setup and are saved entry.data[].

The others options like scan interval which can be edited later are saved in entry.options[]

Can you try the latest version ? 

Regards

**Comment by nicmela** [comment]
It's working 👍 

Thank you!
